/**:
  ros__parameters:
    pub_rate: 1.0
    path: RebotArm
    hardware:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Hardware
      startswith: ["rebotarm/hardware"]
    joints:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Joints
      startswith: ["rebotarm/joints/"]
    gripper:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Gripper
      startswith: ["rebotarm/gripper"]
    bus:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Bus
      startswith: ["rebotarm/bus/"]
    system:
      type: diagnostic_aggregator/GenericAnalyzer
      path: System
      startswith: ["rebotarm/system/"]
