/**:
  ros__parameters:
    pub_rate: 1.0
    path: RebotArm
    control:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Control
      startswith: ["rebotarm/control"]
    hardware:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Hardware
      startswith: ["rebotarm/hardware"]
    joints:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Joints
      startswith: ["rebotarm/joints/"]
    gripper:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Gripper
      startswith: ["rebotarm/gripper"]
    link:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Link
      startswith: ["rebotarm/link/"]
    system:
      type: diagnostic_aggregator/GenericAnalyzer
      path: System
      startswith: ["rebotarm/system/"]
